baseURL = 'https://nspavlo.github.io/'
languageCode = 'en-us'
title = 'JP'
theme = 'paper'

[params]
twitter = 'JansPavlovs'
github = 'nspavlo'
name = 'Jans Pavlovs'
bio = 'Tips and techniques for iOS development.'