# main
title = 'JP'
baseURL = 'https://nspavlo.github.io/'
languageCode = 'en-us'
theme = 'paper'

[params]
  # header socials
  twitter = 'JansPavlovs'
  github = 'nspavlo'

  # home page
  name = 'Jans Pavlovs'
  bio = 'Tips and techniques for iOS development.'

  # misc
  disableHLJS = true
  monoDarkIcon = true